Repository scobca/opd-professional-score-frontend, pull requests merged in 2025-03, with the labels that each got.

#51 added a profile-update file
  .DS_Store
  assets/.DS_Store
  ava.webp
  scriptph.js
  src/.DS_Store
  style/styles.css
  user-profile-update.html
Labels: enhancement

#54 Feat | Profession form
  .idea/inspectionProfiles/Project_Default.xml
  new-profession-form.html
  style/styles.css
Labels: enhancement

#56 fix | email confirmation
  email-verify.html
  js/auto-focus.js
Labels: bug, enhancement

#63 Profession block implementation
  .gitignore
  src/App.vue
  src/assets/css/style.css
  src/components/ProfessionForm.vue
  src/components/UI/inputs/CustomInput.vue
  src/components/UI/inputs/CustomSelect.vue
  src/components/UI/inputs/CustomTextareaInput.vue
  src/main.ts
  src/utils/ApiResolver.ts
Labels: enhancement, vue

#65 Feat | Mock data
  admin-profile.html
  configure-pvk.html
  consultant-profile.html
  expert-profile.html
  index.html
  js/auth.js
  js/auto-focus.js
  moderator-profile.html
  style/admin.css
  style/profile.css
  user-profile.html
Labels: enhancement, Native

#66 Feat pvk form
  .gitignore
  src/api/resolvers/profession/dto/CreateProfession.dto.ts
  src/api/resolvers/profession/profession.resolver.ts
  src/api/resolvers/professionStatistic/dto/CreateProfessionStats.dto.ts
  src/api/resolvers/professionStatistic/dto/GetOldPvk.dto.ts
  src/api/resolvers/professionStatistic/professionStatistic.resolver.ts
  src/api/resolvers/pvk/dto/FullPvkStructure.dto.ts
  src/api/resolvers/pvk/dto/PvkOptionStructureDto.ts
  src/api/resolvers/pvk/pvk.resolver.ts
  src/components/ProfessionForm.vue
  src/components/UI/inputs/CustomInput.vue
  src/pages/PvkSetupPage.vue
Labels: enhancement

#77 Fix lab 2
  src/api/resolvers/profession/dto/output/GetProfessionById.dto.ts
  src/api/resolvers/professionStatistic/dto/input/GetProfessionalStatistic.dto.ts
  src/api/resolvers/professionStatistic/dto/output/CreateProfessionStats.dto.ts
  src/api/resolvers/professionStatistic/dto/output/GetOldPvk.dto.ts
  src/api/resolvers/professionStatistic/professionStatistic.resolver.ts
  src/pages/ProfessionPage.vue
  src/pages/PvkSetupPage.vue
Labels: bug, enhancement

#78 Refactor api resolver
  src/api/apiConf.ts
  src/api/dto/common/default-output.dto.ts
  src/api/dto/pvk-option-structure.dto.ts
  src/api/dto/universal-statistic-collection.dto.ts
  src/api/resolvers/profession/dto/input/create-profession.dto.ts
  src/api/resolvers/profession/dto/input/updatable-profession-values.dto.ts
  src/api/resolvers/profession/dto/input/update-profession.dto.ts
  src/api/resolvers/profession/dto/output/create-pull-of-professions-body-output.dto.ts
  src/api/resolvers/profession/dto/output/get-profession-output.dto.ts
  src/api/resolvers/profession/dto/output/update-profession-body-output.dto.ts
  src/api/resolvers/profession/profession.resolver.ts
  src/api/resolvers/professionStatistic/dto/input/get-old-stats-input.dto.ts
  src/api/resolvers/professionStatistic/dto/input/get-profession-statistics-input.dto.ts
  src/api/resolvers/professionStatistic/dto/output/CreateProfessionStats.dto.ts
  src/api/resolvers/professionStatistic/dto/output/GetOldPvk.dto.ts
  src/api/resolvers/professionStatistic/dto/output/create-profession-stats-output.dto.ts
  src/api/resolvers/professionStatistic/dto/output/get-old-stats-output.dto.ts
  src/api/resolvers/professionStatistic/professionStatistic.resolver.ts
  src/api/resolvers/pvk/dto/CreatePvk.dto.ts
  src/api/resolvers/pvk/dto/FullPvkStructure.dto.ts
  src/api/resolvers/pvk/dto/PvkOptionStructureDto.ts
  src/api/resolvers/pvk/dto/input/full-pvk-structure-input.dto.ts
  src/api/resolvers/pvk/pvk.resolver.ts
  src/components/ProfessionEditForm.vue
  src/components/ProfessionsList.vue
  src/components/ProfessionsManagerList.vue
  src/components/UI/ProfessionsManagerElement.vue
  src/pages/PersonalAccount.vue
  src/pages/ProfessionPage.vue
  src/pages/PvkSetupPage.vue
  src/utils/ApiResolver.ts
Labels: enhancement, vue

#80 refactor(app): code refactoring
  src/App.vue
  src/components/HelloWorld.vue
  src/components/PopUp.vue
  src/components/UI/AppHeader.vue
  src/components/UI/CommonButton.vue
  src/components/UI/FlipCard.vue
  src/components/UI/TestManagerElement.vue
  src/components/UI/UserManagerElement.vue
Labels: enhancement, vue

#81 Feat implements password changing
  src/api/resolvers/profession/profession.resolver.ts
  src/api/resolvers/professionStatistic/professionStatistic.resolver.ts
  src/api/resolvers/pvk/pvk.resolver.ts
  src/api/resolvers/user/dto/output/change-password-second-step-output.dto.ts
  src/api/resolvers/user/user.resolver.ts
  src/assets/icons/arrow-left-icon.svg
  src/components/UI/inputs/CustomInput.vue
  src/pages/CodeVerification.vue
  src/pages/LogIn.vue
  src/pages/PasswordChanging.vue
  src/router/router.ts
Labels: enhancement, ready for merge

#82 Popups recreation
  package-lock.json
  package.json
  src/App.vue
  src/assets/icons/check-icon.svg
  src/assets/icons/cross-icon.svg
  src/components/PopUp.vue
  src/components/RoleSelectForm.vue
  src/components/UI/popups/ErrorPopup.vue
  src/components/UI/popups/InfoPopup.vue
  src/main.ts
  src/pages/LogIn.vue
  src/pages/PasswordChanging.vue
  src/pages/PersonalAccount.vue
  src/pages/RegistrationFirstStep.vue
  src/pages/RegistrationSecondStep.vue
  src/store/event-bus.ts
  src/store/popup.store.ts
  src/store/store.config.ts
  src/utils/popUpState.ts
Labels: enhancement, vue

#84 Feat | Smart professional characteristics selection
  .gitignore
  admin-profile.html
  configure-pvk.html
  expert-profile.html
  index.html
  js/admin.js
  js/configure-pvk.js
  js/expert.js
  js/moderator.js
  js/profession.js
  js/utils-gamma.js
  moderator-profile.html
  style/profile.css
  style/pvk.css
Labels: enhancement, ready for merge, Native

#85 Feat | Smart search
  .gitignore
  package-lock.json
  package.json
  src/App.vue
  src/api/apiConf.example.ts
  src/api/dto/pvk-option-selected-structure.dto.ts
  src/api/dto/pvk-option-structure.dto.ts
  src/api/resolvers/profession/profession.resolver.ts
  src/components/ProfessionForm.vue
  src/components/SocketTest.vue
  src/components/UI/inputs/CustomInput.vue
  src/main.ts
  src/pages/PersonalAccount.vue
  src/pages/ProfessionPage.vue
  src/pages/PvkSetupPage.vue
  src/services/user.ts
  src/utils/userState/UserState.ts
  src/utils/userState/UserState.types.ts
  tsconfig.json
Labels: enhancement

#87 Refactor/app refactoring
  src/api/dto/common/default-error.dto.ts
  src/components/ProfessionForm.vue
  src/components/ProfessionsList.vue
  src/components/ProfessionsManagerList.vue
  src/components/TestsScoreList.vue
  src/pages/PersonalAccount.vue
  src/pages/PersonalAccountPage.vue
  src/pages/ProfessionPage.vue
  src/pages/PvkSetupPage.vue
  src/pages/RegistrationFirstStep.vue
  src/pages/RegistrationSecondStep.vue
  src/pages/archive/AdminPersonalAccount.vue
  src/pages/archive/ConsultantPersonalAccount.vue
  src/pages/archive/ExpertPersonalAccount.vue
  src/pages/archive/UserPersonalAccount.vue
Labels: bug, enhancement, vue

#89 fix(professions): fixed condition for profession visibility
  src/components/ProfessionsList.vue
Labels: bug

#90 Feat/update tab name
  package-lock.json
  src/App.vue
  src/index.html
  src/router/router.ts
  vite.config.ts
Labels: enhancement, ready for merge, vue

#91 fix(professions): updated displaying professions & theirs PVK
  src/components/ProfessionsManagerList.vue
  src/pages/ProfessionPage.vue
Labels: bug, enhancement

#92 Refactor/auth model update
  src/api/resolvers/auth/auth.resolver.ts
  src/api/resolvers/auth/dto/input/auth-user-input.dto.ts
  src/api/resolvers/auth/dto/output/login-user-output.dto.ts
  src/api/resolvers/auth/dto/output/reg-user-first-step-output.dto.ts
  src/api/resolvers/auth/dto/output/reg-user-second-step-output.dto.ts
  src/api/resolvers/auth/dto/output/send-code-again-output.dto.ts
  src/api/resolvers/auth/dto/output/user-data-output.dto.ts
  src/api/resolvers/user/dto/input/user-data-input.dto.ts
  src/api/resolvers/user/user.resolver.ts
  src/components/UI/AppHeader.vue
  src/pages/CodeVerification.vue
  src/pages/LogIn.vue
  src/pages/LogInPage.vue
  src/pages/PasswordChanging.vue
  src/pages/PersonalAccount.vue
  src/pages/RegistrationFirstStep.vue
  src/pages/RegistrationPage.vue
  src/pages/RegistrationSecondStep.vue
  src/router/router.ts
  src/services/auth.ts
Labels: bug, enhancement, vue
